### ISSUE TITLE
The latest Atomes (Version1.1.9) in my PC cannot open xyz file with more than one step

### ISSUE THREAD

**Issue by sailangyf** [Slookeur/Atomes#14]
Hello, Dr. Slookeur
I cannot wait to install the latest Atomes (version 1.1.9). Thanks for your effort some bugs have been fixed, however, I met with a new issue and I don't know whether it's a bug or there is just something wrong with my device. I can open an XYZ file with only one frame but Atomes (version 1.1.9) would crash when I open an XYZ file with more than one frame (e.g. a file with lots of MD steps).
I upload a ZIP file with three XYZ files, test.xyz is an MD simulation with one step, test1.xyz and test2.xyz both are MD simulations with more than one step. Can you test it and help me find the issue? Thank you very much.
In addition, my PC's CPU (with GPU) is AMD 5600G, RAM is 16GB, ROM is 1TB.
Sincerely,
Sailang
[test.zip](https://github.com/Slookeur/Atomes/files/9925875/test.zip)

**Comment by Slookeur** [comment]
Hello, 
thank you for reporting this bug, I corrected the problem (that was not happening on the Linux side). 
I uploaded a new version (1.1.10) check the website to download the update.
Also I will not be able to provide new release for some time (wrist surgery coming up on Monday 7/11) 
but if you find other bugs do not hesitate to report them, I will take care of it when possible.

S.

**Comment by sailangyf** [comment]
Hi, Dr. Slookeur
Thanks for fixing it such quickly. I respect your devotion. I'm sorry to hear it. Wish you all the best. 
Sincerely,
Sailang
