### ISSUE TITLE
calc/cpmd/cpmd_print.c: 2 * duplicated condition warning

### ISSUE THREAD

**Issue by dcb314** [Slookeur/Atomes#17]
calc/cpmd/cpmd_print.c:247:36: warning: duplicated 'if' condition [-Wduplicated-cond]
calc/cpmd/cpmd_print.c:251:36: warning: duplicated 'if' condition [-Wduplicated-cond]

Source code is

   if (tmp_cpmd -> calc_type == 0)
    {
      i = TSTPO;
    }
    else if (tmp_cpmd -> calc_type == 0)
    {
      i = TSTPG;
    }
    else if (tmp_cpmd -> calc_type == 0)
    {
      i = TSTPC;
    }

Suggest code rework.

**Comment by Slookeur** [comment]
Thank you for pointing this out !
Not to mention the useful compiler flag that I did not know ;-)

Will take care of it ASAP !

**Comment by Slookeur** [comment]
Done !
And it helped to correct few other mistakes. 

Thank you very much !

**Comment by dcb314** [comment]
You are very welcome. 

I have not yet persuaded gcc developers to add -Wduplicated-cond to -Wall,
so more people can use this flag.
