### ISSUE TITLE
Fortran files with preprocessor directives should be .F90

### ISSUE THREAD

**Issue by fxcoudert** [Slookeur/Atomes#2]
The following files in `src/fortran/` have preprocessor directives, and should be `.F90` and not `.f90`:

```
angles.f90
bonds.f90
chains.f90
dmtx.f90
gr.f90
initchains.f90
initrings.f90
molecules.f90
msd.f90
parameters.f90
rings-guttman.f90
rings-king.f90
rings-primitive.f90
sk.f90
spherical.f90
```

**Comment by Slookeur** [comment]
I did this a long time ago for various reasons, not needed anymore, and forgot to change it back, thanks ;-)
