### ISSUE TITLE
Cann't Zoom in/out 'Toolboxes' on Windows11 laptop 

### ISSUE THREAD

**Issue by sailangyf** [Slookeur/Atomes#20]
Hi Dr. Sébastien Le Roux,

I found a problem with Atomes 1.1.14 (Windows 64bit):

The window of Toolboxes can't  be zoomed in/out, therefore I can't control it and plot the results.
I suspect it was possibly resulted by high dpi of my laptop screen?

BR,
Fan

**Comment by Slookeur** [comment]
Hello,
could you please attach a screen capture to illustrate the problem ?
Thanks in advance.

**Comment by sailangyf** [comment]
![image](https://github.com/Slookeur/Atomes/assets/67216677/96ebea2d-bbd7-4318-b3f3-df60f54a877f)
 Sure, the snapshot is like this.

I can not adjust the windows of Toolbox, so I can't click to plot the result and export the result.
If you need more information, pls let me know.

BR,
Fan

**Comment by Slookeur** [comment]
Thank you, 
I will check how this looks like on a windows PC of my own as soon as possible, 
it looks like a theme issue, I guess it is always something you can run into when you decided
on the size of a window, in the next release I will try to improve things. 
In the mean tine you can still activate the short cut to open the curve window, as long as you 
can select the line you are interested in (using arrow you can up or down), then simply press 
space or enter to open the selected window, you will need to use your keyboard but it will work. 

Thank you again for letting me know.

**Comment by sailangyf** [comment]
Thank you very much for getting back to me so quickly.
Unfortunately, I don't know why I also can't activate the shortcut to open the curve window using the keyboard. It's really strange, because in the previous Atomes versions, I am sure I could control it.
I am willing to help to locate the problem if any information is required.

**Comment by sailangyf** [comment]
![image](https://github.com/Slookeur/Atomes/assets/67216677/bbb9321a-46fc-4023-8497-9f84a351f6bd)
Hello,
I tried the latest Atomes for Ubuntu22.04 as well, but I came across the same problem. I can't do anything to adjust the window of Toolboxes. I can unfold or fold the items, but can't show and plot any calculation results.
It's very strange. Has anyone met with the same situation?

**Comment by sailangyf** [comment]
Hi,

It appears that the display of the Toolboxes window is related to the screen resolution and scaling factor on my device.

Specifically, my screen resolution is 2880x1800, and when the screen scaling is set to 175%, the Toolboxes window is not fully displayed. However, when I adjust the scaling to 200%, the Toolboxes window is able to be fully displayed.

I wanted to bring this to your attention and suggest that it might be worth considering adaptations for high-resolution displays, or potentially allowing the Toolboxes window to be freely resizable, in order to ensure a more consistent user experience across different hardware configurations.

Thank you for your attention to this matter.
