### ISSUE TITLE
Unable to open Atomes on Win11 24H2

### ISSUE THREAD

**Issue by sailangyf** [Slookeur/Atomes#22]
Hi Dr. Sébastien Le Roux,

I am not sure if it's a bug or just because Atomes was never designed for Win11, I can't open Atomes after I installed the latest Atomes. 

In the past, I could run Atomes on my Win11 PC. Recently, I upgraded my Win11 version to the latest Win11 24H2 and I also came across a new release of Atomes. However, I can't open Atomes then and I tried many times-uninstall and install. Is there anyone else come across the same problems? Or how can I fix it?

Best regards,
Fan

**Comment by Slookeur** [comment]
Hello, 
I would need more information from you to be able to help, first of all atomes should work on Win11, 
which package did you download and install ? 
I recommend this one: 
[https://sourceforge.net/projects/atomes/files/Windows/atomes-latest-setup-no-win.exe/download](
https://sourceforge.net/projects/atomes/files/Windows/atomes-latest-setup-no-win.exe/download)

Please let me know what happen and I will try to help you out from there, in the mean time I will ask to other Windows 11 users if they have issues. 

Regards

**Comment by sailangyf** [comment]
Hi,

Thanks for your reply. I have already tried the package you recommended, but it still crashed when opening. This happened after I upgraded the windows11 version to 24H2, I am not sure if the problem it's related to the windows side. I am sure I can use Atomes in previous win11.

Best regards

**Comment by Slookeur** [comment]
Ok, 
the new version of atomes now uses an OpenGL testing utility that is launched by atomes,
but before to start the main interface of the software, that is likely failing if the program stops.
Could you please do the following:

1) If you do not have a Linux like command line tool for windows install one,
you could try the next steps with windows built-in tools but I am not familiar with these.

Ex: MSYS2: https://www.msys2.org/

2) (Once installed) Opened the command line and navigate to C:\Program Files\atomes\bin
likely entering something like:
```
]$ cd /c/Program\ Files\atomes\bin
```
3) Then enter:
```
]$ ./atomes_startup_testing.exe
```
And let me know what appear.

3) Then try:
```
]$ ./atomes.exe
```
And let me know what appear (should be similar).
I will see what to do from this point forward, I am sorry for the problem you are facing.

Regards.

**Comment by sailangyf** [comment]
Hi,

Thank you for your detailed instructions. When I entered the command "./atomes_startup_testing.exe", an Atomes app window appeared but disappeared immediately. I tried this several times, every time it was the same situation. 

And then I also tried "./atomes.exe", however, I didn't even observe a flashing window.

Hope it will be helpful. Thanks a lot.

BR

**Comment by Slookeur** [comment]
Hi, 
could you replace the file `atomes_startup_testing.exe` by this one: 

[https://ipcms-cloud.u-strasbg.fr/owncloud/s/ty1PQ6LGOOqjfBA](https://ipcms-cloud.u-strasbg.fr/owncloud/s/ty1PQ6LGOOqjfBA)

And let me know what you read with the previous command:
 
```
]$ ./atomes_startup_testing.exe
```

**Comment by sailangyf** [comment]
Sure,
 it returned this info to me:
"
(process:14324): GLib-GIO-WARNING **: 12:47:35.103: win32 session dbus binary not found
opengl_visual= 1, status= 0
"

**Comment by Slookeur** [comment]
Ok, 
not sure if the warning matters, what I am sure it that the other message is appropriate, 
so as a last chance you might want to try the other installation package (that includes more Windows
dependencies but likely Windows10 only, I guess it is worth a try ...) I would need access to a Windows
11 computer to help you out, but I do not have one (so far) so you will have to patient, sorry. 
I will try my best to help you as soon as possible.

Best regards.

**Comment by sailangyf** [comment]
Thank you very much for your attention. In fact, I tried both and both failed. : (
Thank you again. Looking forward to a compatible version.

Best regards,

**Comment by Slookeur** [comment]
Hello, 
some updates on your case I think : you can run the latest version of **atomes** on Windows11 using msys2, 
if you installed it, then open **atomes** via the terminal, it will work. 
I tested it this morning with the help of a student who also has issue with Windows11, no way to launch **atomes** via double-click on the desktop icon (or any short-cut for that matter) but it works via the terminal. 
I will search for help on that matter, but I have no issue what so ever on Windows10,
will let you know when I have a proper fix (I hope it does not require a Windows11 to build the software).

I built a GTK4 version that seems to work properly on Windows11, I will update the download to make these packages available.

**Comment by sailangyf** [comment]
Hi,

Thanks  a lot! New GTK4 version works for me. I really appreciate it.

Best regards,
Fan

**Comment by Slookeur** [comment]
I fixed the Win11 issue including with the GTK3 version, check the website to download the latest package.
