### ISSUE TITLE
The software cannot be opened normally

### ISSUE THREAD

**Issue by ysu-ctl** [Slookeur/Atomes#23]
Dear Dr. Sebastien Le Roux
I downloaded the latest version of Windows software on the website. After installing the win10 21H1 system, it was opened and flashed back immediately without error messages. Neither installation package can be used normally. Do you have any installation tutorials or precautions for windows?

**Comment by Slookeur** [comment]
Hello, 
sorry about that, some Windows11 users are also facing the same issue, but I have none on my Windows10.
I am working on the problem and will let you know how use the software normally, 
in the mean time you should be able to run it via **msys2**

[ https://www.msys2.org/](https://www.msys2.org/)

Install it, then open atomes using the command line: 

```
]$ atomes
```

or 

```
]$ cd /c/Program\ Files/Atomes/bin
]$ ./atomes.exe
```

Let me know if that does the trick.

Also you can download here the old version, could you please let me know if it works properly: 

[https://ipcms-cloud.u-strasbg.fr/owncloud/s/ArAeehYGAKaQ0Ao](https://ipcms-cloud.u-strasbg.fr/owncloud/s/ArAeehYGAKaQ0Aol)

Simply replace the file ```C:\Program Files\Atomes\bin\atomes.exe``` by this one and double click on the Desktop short-cut, thanks in advance.

**Comment by Slookeur** [comment]
I built a GTK4 version that seems to work properly on Windows11, I will update the download to make these packages available.

**Comment by ysu-ctl** [comment]
Dear Dr. Sebastien Le Roux
Thank you very much for your reply. I have downloaded msys2, but the method you suggested still doesn't work. 
The link opening in the old version will not work. Please send it again when convenient.
 In addition, how should I download the GTK4 version?

**Comment by ysu-ctl** [comment]
The installation of Atomes with GTK4 version works fine. Thank you again for your help.

**Comment by Slookeur** [comment]
I fixed the Win11 issue including with the GTK3 version, check the website to download the latest package.
