### ISSUE TITLE
What is the use of -Wl,--export-dynamic ?

### ISSUE THREAD

**Issue by fxcoudert** [Slookeur/Atomes#5]
The `Makefile` for Linux has:

```
  LIBS = -Wl,--export-dynamic $(LGTK) -lm -lgfortran
```

This is not an option accepted by the macOS linker. I can change the Makefile to avoid its use on macOS, but I am not sure why it is needed on Linux in the first place. The GNU ld manual says:

> When creating a dynamically linked executable, add all symbols to the dynamic symbol table. The dynamic symbol table is the set of symbols which are visible from dynamic objects at run time. If you do not use this option, the dynamic symbol table will normally contain only those symbols which are referenced by some dynamic object mentioned in the link. If you use dlopen to load a dynamic object which needs to refer back to the symbols defined by the program, rather than some other dynamic object, then you will probably need to use this option when linking the program itself.

I have not seen anywhere in the code the loading of dynamic objects (with `dlopen`). Is it really needed?

**Comment by Slookeur** [comment]
Probably not then, not sure why it is here, first though is that for some reason, at some point, It got required ... hence I used it ... but If not needed anymore no issue for me ;-)
